### PR TITLE
Slider for featured album on homepage

### PR DESCRIPTION
**Pull request by Klikini**
Provides a new theme setting that takes the name of an album and displays it as a slider at the top of the homepage using [lightSlider](http://sachinchoolur.github.io/lightslider/) instead of listing it with the rest of the albums.

[Demo](https://snaperturephotos.com)

### CODE REVIEW

**Comment by amcolash** [comment]
Very nice looking! I am going to leave @rprieto in charge of approving this one as it is his project. I made the previous theme w/ the exif info, and definitely like this direction.

I suppose I should hack away at some custom css to make my personal gallery look a bit nicer - love the dark twist on yours.

**Comment by Klikini** [comment]
Just pushed a quick change that works around [an issue in lightSlider](https://github.com/sachinchoolur/lightslider/issues/424)

@amcolash Thanks 😄 I'm coming from Zenphoto, where I always used the default dark theme, so it just made me feel more comfortable to change the color variables here. Now I just need to figure out how to allow linking to individual photos and I'm all set!

**Comment by Klikini** [comment]
Since this still appears to be [an issue with LightSlider](https://github.com/sachinchoolur/lightslider/issues/456) and I think it's best to keep using a plugin compatible with LightGallery, I just added some CSS rules to force a constant slider height (defaults to 400px, but can be changed with `@slider-height`).

If this is still a welcome addition, I think that fixes it (see if you can break my [demo](https://snaperturephotos.com/), I haven't been able to yet).

**Comment by rprieto** [comment]
Hi @Klikini, I'm not sure why I'm only seeing your PR now. It's a great feature, thanks for building it!

**Pull request merged**
