### PR TITLE
Justified Albums

### PR DESCRIPTION
**Pull request by amcolash**
Hey @rprieto! I have updated my PR from the cards theme over to here. I don't think you gave me write access like you mentioned, but no worries! I added the justified album list and cleaned up a hack I added for the justified gallery (actually read through their docs this time haha).

You can take a look at what it looks like on heroku: https://thumbsup-testing.herokuapp.com/

### CODE REVIEW

**Comment by amcolash** [comment]
I am not sure if I like the look of the embedded captions for album names. It looks like getting those working with the justified gallery plugin will be a bit of a pain. Can always hide the names, but I am a fan of always seeing album names.

**Comment by rprieto** [comment]
Thanks for porting it over! I gave you write access but it looks like you have to accept the invite (maybe by email, or on https://github.com/thumbsup). 

The theme looks great! I agree it might look better if the caption / number of photos is displayed below the album, black on the white background. I'd be OK to remove the date range if it makes it look better. Let me know when you're OK for me to merge it, and then you can keep working on master!

**Comment by amcolash** [comment]
There are tons of gallery-like npm modules out there (like this https://www.npmjs.com/package/gallerygrid). I think it might make sense to look into one of these in the future to make the titles look nicer. For the time being, I will just remove the dates and I can iterate later on.

**Comment by piccolbo** [comment]
Thanks looks great.

**Pull request merged**
